artifact_location: file:///workspace/physicsnemo/examples/cfd/darcy_nested_fnos/mlruns/0
creation_time: 1763278399667
experiment_id: '0'
last_update_time: 1763278399667
lifecycle_stage: active
name: Default
